[project]
name = "optionflow-amm"
authors = ["Oleg C"]
description = "Options AMM with SIP-010 token support"
license = "MIT"

[contracts.sip-010-trait]
path = "contracts/sip-010-trait.clar"

[contracts.mock-token]
path = "contracts/mock-token.clar"
depends_on = ["sip-010-trait"]

[contracts.option-amm]
path = "contracts/option-amm.clar"
depends_on = ["sip-010-trait", "mock-token"]

