
[node]
working_dir = "/devnet"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
data_url = "http://127.0.0.1:20443"
p2p_address = "127.0.0.1:20443"
miner = true
stacker = true
seed = "3b68e410cc7f9b8bae76f2f2991b69ecd0627c95da22a904065dfb2a73d0585f01"
local_peer_seed = "3b68e410cc7f9b8bae76f2f2991b69ecd0627c95da22a904065dfb2a73d0585f01"
pox_sync_sample_secs = 0
wait_time_for_blocks = 0
wait_time_for_microblocks = 0
next_initiative_delay = 3000
mine_microblocks = false
microblock_frequency = 1000

[connection_options]
# inv_sync_interval = 10
# download_interval = 10
# walk_interval = 10
disable_block_download = false
disable_inbound_handshakes = true
disable_inbound_walks = true
public_ip_address = "1.1.1.1:1234"
auth_token = "12345"

[miner]
first_attempt_time_ms = 500
block_reward_recipient = "ST3Q96TFVE6E0Q91XVX6S8RWAJW5R8XTZ8YEBM8RQ"
microblock_attempt_time_ms = 10
pre_nakamoto_mock_signing = false
mining_key = "19ec1c3e31d139c989a23a27eac60d1abfad5277d3ae9604242514c738258efa01"

[[ustx_balance]]
address = "ST3N7D4F8TDBNPAN7W6CJ5RGF5DAW5MGHNEGTCR6R"
amount = 1000000000000

[[ustx_balance]]
address = "ST3TF2B73R3QVZDF9Z0KE1SR2X3HKZXS6E7R50AW0"
amount = 100000000000000

[[ustx_balance]]
address = "ST3N7D4F8TDBNPAN7W6CJ5RGF5DAW5MGHNEGTCR6R"
amount = 500000000000

[[ustx_balance]]
address = "ST3N7D4F8TDBNPAN7W6CJ5RGF5DAW5MGHNEGTCR6R"
amount = 500000000000

[[events_observer]]
endpoint = "stacks-signer-0.stacks-options.devnet:30000"
events_keys = ["stackerdb", "block_proposal", "burn_blocks"]

# Add orchestrator (docker-host) as an event observer
# Also used by the devnet chainhook instance
[[events_observer]]
endpoint = "host.docker.internal:20445"
events_keys = ["*"]

# Add stacks-api as an event observer
[[events_observer]]
endpoint = "stacks-api.stacks-options.devnet:3700"
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "krypton"
magic_bytes = "T3"
first_burn_block_height = 100
pox_prepare_length = 5
pox_reward_length = 20
burn_fee_cap = 20_000
poll_time_secs = 1
timeout = 2
peer_host = "host.docker.internal"
rpc_ssl = false
wallet_name = ""
username = "devnet"
password = "devnet"
rpc_port = 20445
peer_port = 18444

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
epoch_name = "2.0"
start_height = 100

[[burnchain.epochs]]
epoch_name = "2.05"
start_height = 100

[[burnchain.epochs]]
epoch_name = "2.1"
start_height = 101

[[burnchain.epochs]]
epoch_name = "2.2"
start_height = 102

[[burnchain.epochs]]
epoch_name = "2.3"
start_height = 103

[[burnchain.epochs]]
epoch_name = "2.4"
start_height = 104

[[burnchain.epochs]]
epoch_name = "2.5"
start_height = 108

[[burnchain.epochs]]
epoch_name = "3.0"
start_height = 142

[[burnchain.epochs]]
epoch_name = "3.1"
start_height = 144

[[burnchain.epochs]]
epoch_name = "3.2"
start_height = 146
